title: Shunye Li's Profile
page-top-title: Shunye Li
top-section-bg-text: Academic Homepage
home-subtitle: Shunye Li&ensp;|&ensp;李顺烨
copyright-text: '&copy; Shunye Li 2023-2024. All Rights Reserved.'
